# Generated by Django 4.2.10 on 2026-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
